add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

format = """
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$golang\
$rust\
$custom\
$line_break\
$jobs\
$status\
$character\
"""

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false