# Inserts a blank line between shell prompts
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

format = """
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$golang\
$rust\
$terraform\
$custom\
$cmd_duration\
$line_break\
$jobs\
$time\
$status\
$character"""

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false

[kubernetes]
format = 'on [⛵ $context](dimmed green) '
disabled = false

[time]
disabled = false
